# Generated by Django 2.2.12 on 2022-12-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gaming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gaming',
            new_name='Time',
        ),
    ]
