# Generated by Django 2.2.12 on 2022-12-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20221220_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(verbose_name='Game Time'),
        ),
    ]
