# Generated by Django 2.2.12 on 2022-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221221_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='game',
            name='contents',
            field=models.ManyToManyField(to='main_app.Extra'),
        ),
    ]
