# Generated by Django 2.2.12 on 2022-12-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20221221_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra',
            new_name='Content',
        ),
    ]
